import { Briefcase, FilePlus, LayoutDashboard } from "lucide-react";

export const ROUTES = [
  {
    path: "/",
    // index: true,
    element: "Dashboard",
    roles: ["Admin"],
    isPrivate: true,
    showInSidebar: true,
    label: "Dashboard",
    icon: LayoutDashboard,
  },
  {
    path: "/forgot-password",
    element: "ForgotPassword",
    roles: [],
    isPrivate: false,
    showInSidebar: false,
    label: "Forgot Password",
    icon: LayoutDashboard,
  },
  {
    path: "/reset-password",
    element: "ResetPassword",
    roles: ["admin", "user"],
    isPrivate: false,
    showInSidebar: false,
    label: "Reset Password",
    icon: LayoutDashboard,
  },
  {
    path: "/resend-verification-email",
    element: "ResendVerificationEmail",
    roles: ["admin", "user"],
    isPrivate: false,
    showInSidebar: false,
    label: "Reset Password",
    icon: LayoutDashboard,
  },
  {
    path: "/sendverification-mail",
    element: "SendVerificationMail",
    roles: [],
    isPrivate: false,
    showInSidebar: false,
    label: "SendVerificationMail",
    icon: LayoutDashboard,
  },
  {
    path: "/login",
    element: "Login",
    roles: [],
    isPrivate: false,
    showInSidebar: false,
    icon: LayoutDashboard,
  },
  {
    path: "/signup",
    element: "SignUp",
    roles: [],
    isPrivate: false,
    showInSidebar: false,
    icon: LayoutDashboard,
  },
  {
    path: "/update-email",
    element: "UpdateEmail",
    roles: [],
    isPrivate: false,
    showInSidebar: false,
    icon: LayoutDashboard,
  },
  {
    path: "/verify-email",
    element: "VerifyEmail",
    roles: [],
    isPrivate: false,
    showInSidebar: false,
    icon: LayoutDashboard,
  },
  {
    path: "/",
    // index: true,
    element: "ClientDashboard",
    roles: ["Client"],
    isPrivate: true,
    showInSidebar: true,
    label: "Dashboard",
    icon: LayoutDashboard,
  },
  {
    path: "/",
    element: "BackendDashboard",
    roles: ["Backend Team"],
    isPrivate: true,
    showInSidebar: true,
    label: "Dashboard",
    icon: LayoutDashboard,
  },
  {
    path: "/",
    element: "AgentDashboard",
    roles: ["Agent"],
    isPrivate: true,
    showInSidebar: true,
    label: "Dashboard",
    icon: LayoutDashboard,
  },
  {
    path: "/",
    element: "QCDashboard",
    roles: ["QC"],
    isPrivate: true,
    showInSidebar: true,
    label: "Dashboard",
    icon: LayoutDashboard,
  },
  {
    path: "/verification-cases",
    element: "VerificationCases",
    roles: ["Client", "Backend Team", "Agent","QC"],
    isPrivate: true,
    showInSidebar: true,
    label: "All Cases",
    icon: Briefcase,
  },
  {
    path: "/createnewcase",
    element: "BackendCreateNewCase",
    roles: ["Client", "Backend Team"],
    isPrivate: true,
    showInSidebar: false,
    label: "Create New Case",
    icon: FilePlus,
  },
  {
    path: "/review-confirm/:id",
    element: "ReviewAndConfirm",
    roles: ["Client"],
    isPrivate: true,
    showInSidebar: false,
    label: "ReviewAndConfirm",
    icon: Briefcase,
  },
  {
    path: "/review-confirm/:id",
    element: "BackendReviewAndConfirm",
    roles: ["Backend Team"],
    isPrivate: true,
    showInSidebar: false,
    label: "ReviewAndConfirm",
    icon: Briefcase,
  },
  {
    path: "/review-confirm/:caseId",
    element: "QcReviewAndConfirm",
    roles: ["QC"],
    isPrivate: true,
    showInSidebar: false,
    label: "ReviewAndConfirm",
    icon: Briefcase,
  },
  {
    path: "/review-confirm/:caseId",
    // index: true,
    element: "AgentReviewAndConfirm",
    roles: ["Agent"],
    isPrivate: true,
    showInSidebar: false,
    label: "ReviewAndConfirm",
    icon: Briefcase,
  },
  {
    path: "/profile",
    element: "Profile",
    roles: ["Admin", "Client", "Backend Team", "Agent", "QC"],
    isPrivate: true,
    showInSidebar: false,
    label: "Profile",
    icon: Briefcase,
  },
  {
    path: "/branches/:branchId",
    element: "BranchList",
    roles: ["Client"],
    isPrivate: true,
    showInSidebar: false,
    label: "Branches",
    icon: Briefcase,
  },
  {
    path: "/userslist",
    element: "UserList",
    roles: ["Admin"],
    isPrivate: true,
    showInSidebar: true,
    label: "Users List",
    icon: Briefcase,
  },
  {
    path: "/clientlist",
    element: "ClientList",
    roles: ["Admin"],
    isPrivate: true,
    showInSidebar: true,
    label: "Clients List",
    icon: Briefcase,
  },
];
